// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Bool is a custom type that can unmarshal from both JSON booleans and integers (0/1).
type Bool bool

func (b *Bool) UnmarshalJSON(data []byte) error {
	// Try unmarshaling as a bool first
	var boolVal bool
	if err := json.Unmarshal(data, &boolVal); err == nil {
		*b = Bool(boolVal)
		return nil
	}

	// If that fails, try unmarshaling as an int
	var intVal int
	if err := json.Unmarshal(data, &intVal); err == nil {
		if intVal == 0 {
			*b = false
		} else {
			*b = true
		}
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into Bool", string(data))
}

func (b Bool) ToPointer() *Bool {
	return &b
}
